name: Deploy to Proxmox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/proxmoxapi
            git pull
            source .venv/bin/activate
            pip install -r requirements.txt
            systemctl restart proxmoxapi
